language: java

install: mvn install -DskipTests=true -Dgpg.skip=true

before_install:
  - sudo pip install codecov

after_success:
  - codecov
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
  

jdk:
  - oraclejdk8
